### ISSUE TITLE
Cannot update the gateway

### ISSUE THREAD

**Issue by rosslyn-cuongle** [Microsoft/PowerBI-Cli#23]
I tried to update credential for gateway and get exception as below:

C:\devtools\Console2>powerbi update-connection -d 7f2c6564-57a3-4858-84b2-b9ec81484b6f -u [username] -p [password]
[ powerbi ] Found dataset!
[ powerbi ] Id: 7f2c6564-57a3-4858-84b2-b9ec81484b6f
[ powerbi ] Name: TFLSpend
[ powerbi ] Found 1 Datasources for Dataset 7f2c6564-57a3-4858-84b2-b9ec81484b6f
[ powerbi ] --------------------------------------------------------------------
[ powerbi ] Datesource ID:  69daa095-ab7c-4484-a3bf-d8d6cccc0d8f
[ powerbi ] Gateway ID:  cc061ab1-9d1b-49f3-979d-c3a851fd7db9
[ powerbi ] Credential Type:  undefined
[ powerbi ] Datasource Type:  Sql

TypeError: undefined is not a function
    at C:\Users\cuong.le\AppData\Roaming\npm\node_modules\powerbi-cli\lib\cli-update-connection.js:102:28
    at C:\Users\cuong.le\AppData\Roaming\npm\node_modules\powerbi-cli\node_modules\powerbi-api\lib\autorest\operations\gateways.js:158:14
    at retryCallback (C:\Users\cuong.le\AppData\Roaming\npm\node_modules\powerbi-cli\node_modules\ms-rest\lib\filters\exponentialRetryPolicyFilter.js:140:9)
    at handleRedirect (C:\Users\cuong.le\AppData\Roaming\npm\node_modules\powerbi-cli\node_modules\ms-rest\lib\filters\redirectFilter.js:36:9)
    at Request._callback (C:\Users\cuong.le\AppData\Roaming\npm\node_modules\powerbi-cli\node_modules\ms-rest\lib\requestPipeline.js:125:16)
    at Request.self.callback (C:\Users\cuong.le\AppData\Roaming\npm\node_modules\powerbi-cli\node_modules\ms-rest\node_modules\request\request.js:200:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (C:\Users\cuong.le\AppData\Roaming\npm\node_modules\powerbi-cli\node_modules\ms-rest\node_modules\request\request.js:1067:10)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (C:\Users\cuong.le\AppData\Roaming\npm\node_modules\powerbi-cli\node_modules\ms-rest\node_modules\request\request.js:988:12)

I guess the problem lies on the Credential Type is undefined, is there any param that we can specify the credential type

**Comment by wbreza** [comment]
Looks like we have a bug in the CLI where it attempts to execute a callback that is not defined.  Can  you verify to see if the command worked.  We'll be pusing out an update soon to correct this issue.

**Comment by wbreza** [comment]
Fixed in #24

**Comment by wbreza** [comment]
@rosslyn-cuongle We have deployed a fix to the CLI to provide better error handling.  Please try your update again and report back with any issues.

**Comment by wbreza** [comment]
Closing since we haven't heard back.  Let us know if you are still experiencing this issue.
